### ISSUE TITLE
Do filters inside map function 

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty-puppet#3] opened 2018-07-04 15:34 UTC
Recently we observed memory leak issue when using the padchat. Then I found this piece of code, seems like we are doing find after we load all the contact information. Here is the code:

https://github.com/Chatie/wechaty-puppet/blob/e590d7779205150586c60909675a4bc5bfaddf3a/src/puppet.ts#L491-L522

I think it would be better that we do the filters inside the map function, immediately after we get the payload, we do the filter function on the payload, if the payload is the one we are trying to find, then we return it, otherwise we will return null or undefined. Then we do a filter outside the map function. 

What do you think @zixia

**Comment by zixia** [comment] 2018-07-04 17:50
Could you please describe the "memory leak" issue in details?

I could not understand it if there have no enough information.

**Comment by windmemory** [comment] 2018-07-05 01:38
Sorry for the un-clear description. It's the same to this issue: https://github.com/Chatie/wechaty/issues/1435

I might use the wrong term to describe my problem. It is javascript heap out of memory.

**Comment by zixia** [comment] 2018-07-05 02:46
Yes, it's `heap`, not `leak`.

And could you explain why do you think your modification is related to the Heap OOM problem?

**Comment by windmemory** [comment] 2018-07-05 05:28
We are using name to search the contact, so it will load the whole contact list for the current bot. Then check if any contact has the name that matches the one I am trying to find. 

Currently the find function is loading all the contact information first, then do the search in the contact list, as you can see in the code:
```javascript
searchIdList.map( 
           async id => { 
             try { 
               const payload = await this.contactPayload(id) 
               return payload 
             } catch (e) { 
               // compatible with {} payload, which means that 
               // contact id is not friend with the current user 
               log.silly('Puppet', 'contactSearch() contactPayload exception: %s', e.message) 
               return {} as any 
             } 
           }, 
```

Then the code did the find operation here:
```javascript
     const filterFuncion: ContactPayloadFilterFunction = this.contactQueryFilterFactory(query) 
  
     const idList: string[] = searchContactPayloadList 
                     .filter(filterFuncion) 
                     .map(payload => payload.id) 
```

So my guess is if we do the search when we loading the payload for the contact, and we drop the payload if it doesn't match, it might save some space of the memory. 

Alternative solution for this problem might be create an index from contact name to contact id, then use the id to search the contact, that will avoid this problem.

I also tried to get the contact id and use it to do the search, but the id is not available in current API, this might also be a solution for my problem.

**Comment by windmemory** [comment] 2018-07-06 05:46
@zixia Any thoughts on this issue?

**Comment by zixia** [comment] 2018-07-06 05:54
Short answer: no, your modification will not save any memory usage.

Long answer: 

1. Node.js is using the V8 engine, it will do Garbage Collection period. Once we load a data into memory, even we drop the reference of it, it will not be able to free at once.
1. Even we drop the reference in the map/reduce loop as you mentioned, it will not be able to GC-ed because we still have others' reference to the object, for example, the LRU cache, which will refer to the object, until the object will not be used after 1 hour.

So I believe you have to find other ways to resolve your problem.

**Comment by windmemory** [comment] 2018-07-06 06:18
I agree that the Garbage Collection periodically, so if we drop the reference of it, the memory won't be collected immediately, and right, the modification won't save memory usage, the usage will be the same. But the problem I am running into is heap OOM, which from my understanding, we are holding too much data in memory, and the memory is not able to save more data into it. 

As my understanding, besides periodically triggered, Garbage Collection will be triggered when the heap is full, and it will try to find the garbage to clean. If we hold all the data reference, then the Garbage Collector can not do anything about the memory full, right? Only if we drop some reference of the data, the Garbage Collection process could find the real garbage, then clean it, so the program could keep running.

**Comment by zixia** [comment] 2018-07-06 06:22
Yes, all your understanding is right.

**Comment by windmemory** [comment] 2018-07-06 06:40
If my understanding is right, then move the search operation into the map will solve the problem.

**Comment by zixia** [comment] 2018-07-06 07:09
Sorry, but I don't think so.

If you can confirm that, please let me know.

**Comment by zixia** [comment] 2018-07-07 03:37
@windmemory I had tried your suggestion by moving the filter function into the map like the following code:

```js
const searchContactPayloadList = (yield Promise.all(searchIdList.map((id) => __awaiter(this, void 0, void 0, function* () {
    try {
        const payload = yield this.contactPayload(id);
        if (filterFunction(payload)) {
            return payload
        } else {
            return {};
        }
    }
    catch (e) {
        // compatible with {} payload, which means that
        // contact id is not friend with the current user
        config_1.log.silly('Puppet', 'contactSearch() contactPayload exception: %s', e.message);
        yield this.contactPayloadDirty(id);
        return {};
    }
})))).filter(payload => Object.keys(payload).length > 0);
```

It still OOM with 12GB memory by starting it with `node --max-old-space-size=12196 -r ts-node/register examples/self-testing-bot`.

Here's the 13GB dumped memory core file:

```sh
$ ls -lh core                                                                           
-rw------- 1 zixia zixia 13G Jul  7 03:27 core
```

### Conclusion

1. There's some operation outside the function `contactSearch ()` that caused the OOM problem (too).
1. Your suggestion is valuable, but it can not fix this OOM
1. We need to continue investigating this issue to collect the related evidence and search for possible solutions
1. We have to test our idea in code before we think something "should work" or "should fix" or "should be".

**Comment by zixia** [comment] 2018-07-11 09:33
The last code had included this proposal, please feel free to let me know if you have more thoughts about it.

**Comment by windmemory** [comment] 2018-07-11 10:22
The code looks good, does it solve some of the OOM issue?

**Comment by zixia** [comment] 2018-07-11 11:17
My reply on Jul 7 had already answered that: it will not solve OOM issue, and I do not know if it could solve _part of it_.

However, the current version have some other modifications, like split the huge array into chunks, and some other improvement.

Please test with the latest code, and feel free to let me know if you have any future questions by file a new issue, with the reproduce steps.

**Comment by windmemory** [comment] 2018-07-11 15:25
_Oh, sorry I didn't know how to reply that comment when I saw it, I was thinking you did a search then get OOM. I checked the `self-testing-bot`, seems like it is loading all the contacts, then my change won't help with that. But if we do a search with a given name, I think that could avoid the OOM issue._

----

Anyway, I just checked the commits that separate the operation into trunks, since it removes the part that store the payload, I think that would save a lot of memory, and hope that could solve the issue. I will do some testing with the new version and let you know how it works.

**Comment by zixia** [comment] 2018-07-24 07:31
Did you do testing with the new code?

I have not met the OOM problem recently, and please close this issue if you did so.

Thanks.

**Comment by windmemory** [comment] 2018-07-24 17:32
Sorry, haven't got time to test it recently. Maybe it is okay to close this issue since the OOM problem seems to be gone.

**Comment by zixia** [comment] 2018-07-24 18:04
Ok. So I'll close it and let's file a new issue if this problem back again.

**Closed by zixia** 2018-07-24 18:04 UTC
Labels: enhancement
